wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1680768401.22929
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.16
      5: 0.14.1
      8:
      - 1
      - 3
      - 5
