wandb_version: 1

optimizer:
  desc: null
  value: adam
encoder:
  desc: null
  value: resnet50
learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.009104990161406423
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1680768095.349886
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.14.1
      8:
      - 1
      - 3
      - 5
      9:
        1: course_cicd
