name: GitHub Actions Demo
on: [push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        shell: python
        run:  |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a' as f:
            print(f'VAL=true', file=f)
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci.py