name: GitHub Actions Demo
on: [push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: set-var
        shell: python
        run:  |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a' as f:
            print(f'VAL=true', file=f)
      

      #- name: print value of magic command
      #  if: steps.get-magic-value.outcome === 'success' && steps.get-magic-value.outputs.VAL_FOUND == 'true'
      #  run: echo "the value is ${{ steps.get-magic-value.outputs.MAGIC_VAL }}"
